[project]
name = "qyte"
version = "0.0.1"
description = "Qyte is a virtual machine, bytecode and compilation target."
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.11"
